### PR TITLE
introducing problem matchers

### PR DESCRIPTION
**Pull request by softprops**
This change adds a feature common to most of the other setup-{lang} actions which is [problem matchers](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md). Problem matchers adds the ability to register a set of pattern matchers for log output which can then be presented in the github diff ui. 

There are some limitations worth noting. Github Actions problem matchers today only supports one line error messages. Some rust errors can span multiple lines. These matchers make a best effort at provided an minimal valuable feedback cycle for rust errors so that ci failures are visible in inline in the diff in addition to the logs

### CODE REVIEW

**Comment by hecrj** [comment]
Oh, awesome! Didn't hear about these, are they new?

**Comment by softprops** [comment]
not necessarily new but it took a while for them to be formally documented

**Comment by CryZe** [comment]
@softprops Was the cargo-fmt one tested? I can't seem to get it to work:

https://github.com/LiveSplit/livesplit-core/pull/294/checks?check_run_id=401190220#step:4:4

**Comment by CryZe** [comment]
I figured it out. It looks like the \d at the end is only matching against a single digit, instead of multiple.

**Comment by softprops** [comment]
Yea. I did. My tests likely missed this because I tweaked smaller line numbers.

**Comment by softprops** [comment]
I think there's room for improvement but feel a bit bottlenecked on some limitations of problem matchers and rust error tool chain errors https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md

I figured that at a minimum we should extract what value we can since all other setup-xxx-lang actions do the same as a baseline quality of life feature

**Pull request merged**
